### PR TITLE
Sdk style projects

### PR DESCRIPTION
**Pull request by sqeezy**
This PR is ment to change from "old" style msbuild projects to sdk style. In the process we could target netcoreapp3.0 and net472.

@jediwhale For me the first question to answer is whether the "old" style should be removed in complete or kept for now.

### CODE REVIEW

**Comment by sqeezy** [comment]
Will fix #167

**Comment by jediwhale** [comment]
Thanks. I'll review this as soon as I get some free time.

**Comment by sqeezy** [comment]
It's not quite finished yet. I will enable review when I'm. Pretty sure we need to itterate once, as I'm not sure about the structure of projects. Thanks for being so responsive though.

**Comment by sqeezy** [comment]
During this PR I switched the approach of how to integrate multitargetting a bit. I think a squash could help the understadability of this process a lot.

**Comment by jediwhale** [comment]
The current approach to multitargeting was done in a hurry - good to clean this up.

**Comment by sqeezy** [comment]
I'm pretty happy how it is now. If you want something different structure wise just let me know. I think it would be very helpfull to enable some kind of CI for this project. If you want any help with that, l would be happy to set something up.

**Comment by sqeezy** [comment]
There is still one test failing in the storytests, when running under dotnet core. I can't really grasp whats wrong there, or whether the test is supposed to fail. It seems Fit/CompareFloatingPoint is testing comparison of floating point division before and after adding the needed operator. In this case the test failing would be ok. But it seems to work in the full framework build. Can you help me on that? Other then this I'm done I think.
I also set up an Github-Action to do rudimentary testing. For this I could open up a follow up PR if you are interested.

**Comment by jediwhale** [comment]
What is the output of the failing test?

**Comment by sqeezy** [comment]
image

**Comment by jediwhale** [comment]
This is the reason [https://scottdorman.blog/2019/04/03/floating-point-changes-in-net-core-3-0/] I'll have to think about what to do with the test.

**Comment by sqeezy** [comment]
Is there any way that I can help to move this PR forward?

**Comment by jediwhale** [comment]
I have fixed the test - I'll be able to proceed this week.

**Comment by sqeezy** [comment]
Is there any roadmap regarding this being released?

**Comment by jediwhale** [comment]
Binaries have been published to nuget, documentation updates over the next few days

**Comment by sqeezy** [comment]
Could you give me a quick hint  in how to use the new Runner.dll via the fitnesse wiki.
Alternatively Runner could stay an *.exe. That might prevent people from being confused, like I am now.
I don`t quite remember on why I didn`t configure it that way.

**Comment by jediwhale** [comment]
https://fitsharp.github.io/FitSharp/RunTestsWithFitnesse.html

**Comment by sqeezy** [comment]
Thank you. I forgot that netcore isn't a completely new feature.

**Pull request merged**
